version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: sylla
      POSTGRES_PASSWORD: sylla
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: python-inserter
    volumes:
      - ./daily_data:/usr/src/daily_data
      - ./ETL.py:/usr/src/ETL.py
      - ./processed_files.log:/usr/src/processed_files.log
    depends_on:
      - db
    networks:
      - backend
    command: tail -f /dev/null   # garde le conteneur actif

volumes:
  pgdata: {}   # mapping correct

networks:
  backend:
    driver: bridge


