# Image de base Python
FROM python:3.11-slim

# Installer les dépendances système pour psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Installer les packages Python nécessaires
RUN pip install --no-cache-dir psycopg2-binary pandas

# Définir le dossier de travail pour les scripts
WORKDIR /usr/src

# Par défaut, garder le conteneur actif avec bash (mode debug)
CMD ["bash"]

