# Image de base Python
FROM python:3.11-slim

# Installer les dépendances système pour psycopg2
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Installer les packages Python nécessaires
RUN pip install --no-cache-dir psycopg2-binary pandas

# Définir le dossier de travail pour les scripts
WORKDIR /usr/src/insertion_scripts

# Copier les scripts Python dans le conteneur
COPY insertion_scripts/ .

# Par défaut, lancer bash pour pouvoir exécuter les scripts manuellement
CMD ["bash"]